{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file5.Test_Credence_005 object at 0x0000022FD1D44850>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file5.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "5071d4f3-f1fa-4af7-b197-8fb029cca63c-attachment.txt", "type": "text/plain"}], "start": 1691063855366, "stop": 1691063855366, "uuid": "e47e2878-b43a-4dd6-be7f-934d77d02c2e", "historyId": "8705f94e177da364b63b7466b243c483", "testCaseId": "8705f94e177da364b63b7466b243c483", "fullName": "test_file5.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file5"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "DESKTOP-TV0ODVG"}, {"name": "thread", "value": "10412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file5"}]}