{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file5.Test_Credence_005 object at 0x0000015372F625D0>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file5.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "f203ff65-3592-4712-ba56-c5015fd6f958-attachment.txt", "type": "text/plain"}], "start": 1691134343696, "stop": 1691134343696, "uuid": "9cf83d6f-6308-414b-91c8-9e499a1602b5", "historyId": "8705f94e177da364b63b7466b243c483", "testCaseId": "8705f94e177da364b63b7466b243c483", "fullName": "test_file5.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file5"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "DESKTOP-TV0ODVG"}, {"name": "thread", "value": "7384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file5"}]}