{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file5.Test_Credence_005 object at 0x000002F023E9E650>\n\n    def test_mul_004(self):\n        a = 3\n        b = 7\n        mul = a * b\n        print(\"Mul of a and b is :\" + str(mul))\n        if mul == 10:\n            assert True\n        else:\n>           assert False\nE           assert False\n\ntest_file5.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "445815dc-cd38-4ec3-b994-0caff4526e4b-attachment.txt", "type": "text/plain"}], "start": 1691061776327, "stop": 1691061776327, "uuid": "697f6c3b-51f4-4d47-b72e-3dc5307efa97", "historyId": "8705f94e177da364b63b7466b243c483", "testCaseId": "8705f94e177da364b63b7466b243c483", "fullName": "test_file5.Test_Credence_005#test_mul_004", "labels": [{"name": "suite", "value": "test_file5"}, {"name": "subSuite", "value": "Test_Credence_005"}, {"name": "host", "value": "DESKTOP-TV0ODVG"}, {"name": "thread", "value": "8272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file5"}]}